version: '3'

services:
  daily_diet_api_db:
    container_name: daily_diet_db
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=daily_diet_db
